fail_fast: true
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.6
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix]
      # Run the formatter.
      - id: ruff-format
  - repo: local
    hooks:
      # Run the tests
      - id: pytest
        name: pytest
        stages: [pre-commit]
        types: [python]
        entry: pytest
        language: system
        pass_filenames: false
